import type { Archetype } from "@cv-builder/schemas";

export const mobileEngineer: Archetype = {
  id: "mobile-engineer",
  name: "Mobile Engineer",
  description: "iOS/Android engineers building native and cross-platform mobile apps",
  keywords: [
    "ios",
    "android",
    "swift",
    "swiftui",
    "objective-c",
    "uikit",
    "kotlin",
    "jetpack compose",
    "android sdk",
    "xcode",
    "android studio",
    "react native",
    "flutter",
    "dart",
    "kotlin multiplatform",
    "core data",
    "room",
    "coroutines",
    "combine",
    "mvvm",
    "ci/cd",
    "fastlane",
    "app store connect",
    "google play console",
    "testflight",
    "crashlytics",
    "firebase",
    "rest api",
    "push notifications",
    "deep linking",
  ],
  evaluationWeights: {
    shippedEvidence: 0.3,
    quantifiedImpact: 0.2,
    toolingVisibility: 0.2,
    atsCompatibility: 0.1,
    keywordMatch: 0.1,
    publicProof: 0.1,
  },
  actionVerbs: [
    "Shipped",
    "Launched",
    "Released",
    "Migrated",
    "Optimized",
    "Reduced",
    "Refactored",
    "Integrated",
    "Automated",
    "Debugged",
    "Instrumented",
    "Profiled",
  ],
  antiPatterns: [
    "familiar with mobile development",
    "worked on the app",
    "various mobile frameworks",
    "responsible for app maintenance",
    "passionate about mobile technologies",
    "experience with cross-platform development",
  ],
  version: "1.0.0",
};
